apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: client-react
  template:
    metadata:
      name: client-react
      labels:
        app.kubernetes.io/name: client-react
    spec:
      containers:
        - name: client-react
          image: kibolho/fsfc2-client-react
          ports:
            - containerPort: 3000